refactor(typescript): Migrate inline-notice
box/box-ui-elements pull request #2588
Opened 2021-06-03 00:49 UTC by The-Speck

2021-06-09 18:01 UTC, alexkrolick approved these changes

2022-04-25 18:52 UTC, apieceofbart requested changes

2022-04-25 18:52 UTC, apieceofbart commented on src/components/inline-notice/InlineNotice.tsx
> +export enum InlineNoticeType {
how about we use union types instead? I think they're much clearer

2022-04-25 18:52 UTC, apieceofbart commented on src/components/inline-notice/InlineNotice.tsx
> +InlineNotice.displayName = 'InlineNotice';
Why not just use `function InlineNotice...` and get rid of this line?

2026-09-03 13:44 UTC, bonchevskyi commented
Closing since its abandoned PR and also `inline-notice` was migrated recently in [other PR](https://github.com/box/box-ui-elements/pull/4727)

2026-09-03 13:44 UTC, closed without merging