feat(selectable): change single-click from select to navigate behind FF
box/box-ui-elements pull request #3069
Opened 2022-10-03 18:20 UTC by jcamden

LVE FF enabled:
![navigate-on-click](https://user-images.githubusercontent.com/5461045/193648801-140e4c58-7506-4ebf-9d5e-dc8840b88adf.gif)

LVE FF disabled:
![select-on-click](https://user-images.githubusercontent.com/5461045/193648861-11d7117c-5479-439c-8741-a40e0d70acc2.gif)

I tried two other approaches in EUA:
1. creating an alternate `withItemSelection` and changing `onDoubleClick` to `onClick`
    - This was not enough, as the crucial change happens here where something is assigned to `onRowClick`
    - We can still do the above in conjunction with these changes, but probably the best would be to wait until we redact the FF and then simply change `onDoubleClick` to `onClick` both here (`makeSelectable`) and there (`withItemSelection`).
2. wrapping `TableRow` in `ItemLink`, but that road was hard to hoe, and maybe not the best idea (not sure how that could affect the interactivity of `TableRow` descendants.

Please note that this change does not accomplish what is required for Grid View to navigate on click.

2022-10-03 18:46 UTC, ahorowitz123 reviewed
Hmm I thought we had decided to go the route of making a new HOC. I'm not entirely following the reasoning behind using this approach instead.

Also, GridView does use the `handleRowClick` function so I'm confused why this also doesn't work there

2022-10-03 20:50 UTC, ahorowitz123 approved these changes

2022-10-03 22:11 UTC, ahorowitz123 requested changes
On second thought, lets move this logic into EUA by swapping functionality there

2022-10-28 18:20 UTC, greg-in-a-box commented
@jcamden @ahorowitz123 can this PR be closed if the logic will be provided in EUA ?

2023-01-13 18:23 UTC, jcamden commented
> @jcamden @ahorowitz123 can this PR be closed if the logic will be provided in EUA ?

Hi @greg-in-a-box , sorry that I missed this! Yes, this branch can be closed.

2023-01-13 18:23 UTC, closed without merging