build(deps-dev): bump uuid from 3.3.2 to 8.3.2
box/box-ui-elements pull request #3075
Opened 2022-10-05 13:19 UTC by MateuszMamczarz

2022-10-05 16:31 UTC, jstoffan requested changes
We'll need to correct the commit message, as it's not a build-related change. We also need to add BREAKING CHANGE to the description of the commit message. Please see the [Contribution Guide](https://github.com/box/box-ui-elements/blob/master/CONTRIBUTING.md#step-4-push-your-feature-branch-to-your-fork) for more details.

FYI @tjuanitas @greg-in-a-box, as this will affect platform customers.

2022-10-06 10:19 UTC, MateuszMamczarz commented
@jstoffan not sure what what be better instead of `build` here, which one would you pick?

2022-10-06 14:33 UTC, jstoffan commented
Probably just go with `feat`, since I think `chore` may not trigger the parser correctly.

2022-10-06 16:22 UTC, jstoffan approved these changes

2022-10-06 18:54 UTC, greg-in-a-box approved these changes

2022-10-06 19:01 UTC, merged