fix(content-sharing): removed api condition when constructing api
box/box-ui-elements pull request #3251
Opened 2023-02-17 19:10 UTC by greg-in-a-box

stories for this element was not working based on the paragraph in the story because it was not regenerating a new API object when the knobs changed.  After further investigation, the API object should always be provided if the props are not provided to the API constructor.  Error handling happens in the functions

2023-02-17 19:57 UTC, tjuanitas approved these changes

2023-02-17 21:51 UTC, sophiayangyxy approved these changes

2023-02-17 21:57 UTC, Machoper approved these changes

2023-02-21 17:35 UTC, tjuanitas requested changes
slack thread as information that checking `!api` might be necessary (although not the way we're expecting it to be)

in its current form, it looks like this `useEffect` does not do anything because `api` shouldn't be falsey. but removing the `!api` will change the previous behavior and call `setAPI` more, which could introduce a bug

2023-02-21 18:09 UTC, tjuanitas approved these changes

2023-02-21 18:56 UTC, merged