feat(content-explorer-modal): allow rendering within parent
box/box-ui-elements pull request #3449
Opened 2023-10-19 12:34 UTC by dmazaleuskaya

Extended `ContentExplorerModalContainer` and `ContentExplorerModal` components to accept optional `shouldNotUsePortal` to that it's possible to render the modal within the parent, not only in the Portal.

2024-01-26 15:34 UTC, tnastula approved these changes

2024-01-26 16:15 UTC, greg-in-a-box requested changes
In `ContentExplorerModalContainer`, there are two modals, but the prop you added is applying only to the first one, does the second one also need to do the same thing? 

There should also be a test from this level to show that the `ContentExplorerModal` is actually rendering within the parent and not from a portal, since its a feature that is being added.

2024-01-26 17:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/box/box-ui-elements?pullRequest=3449) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/box/box-ui-elements?pullRequest=3449) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: dmazaleuskaya<br/>:x: Darya Mazaleuskaya<br/><hr/>**Darya Mazaleuskaya** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/box/box-ui-elements?pullRequest=3449) it.</sub>

2024-01-29 16:17 UTC, dmazaleuskaya commented
Close in favour of https://github.com/box/box-ui-elements/pull/3501

2024-01-29 16:17 UTC, closed without merging