Fetch avatar with type
box/box-ui-elements pull request #3560
Opened 2024-05-23 16:56 UTC by shahzadaziz

2024-05-28 20:40 UTC, mickr commented
Can you please add a description for the PR?

2024-05-28 22:18 UTC, bfoxx1906 commented on src/components/contact-datalist-item/ContactDatalistItem.tsx
> +    type?: string;
Can type ever be null or undefined? If so we might need to treat this similar to how we do the name e.g. type?: string|null|undefined

2024-05-28 22:33 UTC, greg-in-a-box requested changes
Can we add some more unit tests, the snapshot that was updated is only covering the test coverage from feature level but not at the component level where they could be used in other places outside of USM

2024-05-30 16:03 UTC, shahzadaziz commented
@greg-in-a-box added some tests. Can you take a look.

2024-05-30 18:26 UTC, greg-in-a-box approved these changes

2024-05-30 20:05 UTC, JChan106 approved these changes

2024-05-30 20:18 UTC, merged