Add metadata instance list
box/box-ui-elements pull request #3640
Opened 2024-09-06 21:05 UTC by jankowiakdawid

This PR adds displaying the list of Metadata Instances that were added to a file.

![Screenshot 2024-09-06 at 23 04 13](https://github.com/user-attachments/assets/c0e01163-72d2-48af-a9ee-e0c6ab223677)

![Screenshot 2024-09-06 at 23 04 42](https://github.com/user-attachments/assets/9fdf7895-6e35-4229-bb2a-01110fca9c1d)

![Screenshot 2024-09-06 at 23 04 57](https://github.com/user-attachments/assets/0de3e0db-c3b3-4353-a346-f3a3a298b02f)

2024-09-09 19:13 UTC, greg-in-a-box requested changes

2024-09-09 19:13 UTC, greg-in-a-box commented on src/elements/content-sidebar/MetadataSidebarRedesign.tsx
> +                    )}
can we add some unit tests to account for these conditional statements?

2024-09-11 08:49 UTC, karolinaru commented on src/elements/content-sidebar/stories/MetadataSidebarRedesign.stories.tsx
> +        await canvas.findAllByRole('heading', { name: 'Metadata' });
This find might be deleted

2024-09-11 08:52 UTC, karolinaru commented on src/elements/content-sidebar/stories/MetadataSidebarRedesign.stories.tsx
> +        const addTemplateButton = await canvas.findByRole('button', { name: 'Add template' });
When I deleted the line above in my stories, they sometimes failed to find the button, so I added an additional timeout to ensure we wait for the button to render
`const addTemplateButton = await canvas.findByRole('button', { name: 'Add template' }, { timeout: 5000 });
`

2024-09-17 23:34 UTC, closed without merging