feat(metadata-sidebar): add metadata-editor package
box/box-ui-elements pull request #3645
Opened 2024-09-13 09:12 UTC by wpiesiak

Add [metadata-editor](https://www.npmjs.com/package/@box/metadata-editor) package

2024-09-13 10:46 UTC, jankowiakdawid approved these changes

2024-09-13 16:34 UTC, greg-in-a-box requested changes

2024-09-13 16:34 UTC, greg-in-a-box commented on package.json
> +        "@box/metadata-editor": "^0.45.0"
why are we adding it as a direct dependency?

2024-09-14 00:40 UTC, greg-in-a-box commented
closing in favor of this: https://github.com/box/box-ui-elements/pull/3652

2024-09-14 00:40 UTC, closed without merging