feat(metadata-sidebar): disable delete button
box/box-ui-elements pull request #3677
Opened 2024-09-25 15:39 UTC by karolinaru

This pull request disables the Delete button in the MetadataInstanceEditor when a user starts creating a new template. Since there's nothing to delete before the instance is created, the button stays inactive.

Editing new template chosen from dropdown:
<img width="340" alt="Screenshot 2024-09-25 at 17 01 40" src="https://github.com/user-attachments/assets/00d5e5bd-b085-4e17-bdb3-3c08f518c81c">

Editing already existing instance:
<img width="340" alt="Screenshot 2024-09-25 at 17 01 21" src="https://github.com/user-attachments/assets/66675c08-0a97-4594-90a4-1f05b2d85f5c">

2024-09-25 18:16 UTC, greg-in-a-box requested changes

2024-09-25 18:16 UTC, greg-in-a-box commented on src/elements/content-sidebar/__tests__/MetadataInstanceEditor.test.tsx
we need to add unit tests for when the button is disabled under specific conditions and enabled under different conditions

2024-09-25 20:12 UTC, jankowiakdawid commented on src/elements/content-sidebar/__tests__/MetadataInstanceEditor.test.tsx
we can also add a storybook story to showcase that the button is disabled

2024-09-26 10:19 UTC, karolinaru commented on src/elements/content-sidebar/__tests__/MetadataInstanceEditor.test.tsx
added both unit and storybook tests

2024-09-26 15:14 UTC, jankowiakdawid approved these changes

2024-09-26 17:28 UTC, greg-in-a-box approved these changes

2024-09-26 21:19 UTC, JChan106 approved these changes

2024-09-26 21:19 UTC, merged